version: '3.3'
services:
 web:
# testing the nginx web server
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  networks:
    - mysqlnetwork

 php:
  #image: php:7-fpm
  image: php:7-fpm-sqli
  volumes:
    - ./code:/code
  networks:
    - mysqlnetwork
 mysql:
  image: mysql:5.7
  restart: always
  environment:
    MYSQL_DATABASE: 'latif-mysqldb'
    # So you don't have to use root, but you can if you like
    MYSQL_USER: 'a-latifa'
    # You can use whatever password you like
    MYSQL_PASSWORD: 'Ret0@l012990'
    # Password for root access
    MYSQL_ROOT_PASSWORD: 'Ret0@l012990'
      # Where our data will be persisted
  volumes:
    - latif-mysqldb:/var/lib/mysql
  networks:
    - mysqlnetwork
# Names our volume
volumes:
  latif-mysqldb:
networks:
  mysqlnetwork:
#    name: mysql-network

